version: 2.1
orbs:
  aws-ecr: nonsense/aws-ecr@0.0.1

executors:
  ubuntu:
    docker:
      - image: ubuntu:19.10

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile.lotus
          no-output-timeout: 30m
          path: .
          repo: lotus-test-dev
          skip-when-tags-exist: false
          tag: '${CIRCLE_SHA1:0:8}'
